name: ifba_bot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  faker: ^2.1.0
  mocktail: ^0.3.0

dependencies:
  supabase: ^1.2.0
  puppeteer: ^2.19.0
  teledart: ^0.3.4
  intl: ^0.18.0
  dotenv: ^4.0.1
